// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "auth.proto" (package "auth", syntax proto3)
// tslint:disable
import { SetActionBookletResponse } from "./data_types_requests";
import { SetActionBookletRequest } from "./data_types_requests";
import { GetGatewayEventInfoResponse } from "./data_types_requests";
import { GetGatewayEventInfoRequest } from "./data_types_requests";
import { GetSyncReportResponse } from "./data_types_requests";
import { GetSyncReportRequest } from "./data_types_requests";
import { ActionEventSyncResponse } from "./data_types_requests";
import { ActionEventSyncRequest } from "./data_types_requests";
import { SavePlanRequest } from "./data_types_requests";
import { AddPlan3Request } from "./data_types_requests";
import { AddPlan2Request } from "./data_types_requests";
import { CheckPlanResponse } from "./data_types_requests";
import { CheckPlanRequest } from "./data_types_requests";
import { AddPlan1Request } from "./data_types_requests";
import { SaveCityRequest } from "./data_types_requests";
import { AddCityRequest } from "./data_types_requests";
import { SaveCountryRequest } from "./data_types_requests";
import { AddCountryRequest } from "./data_types_requests";
import { SaveActionEventRequest } from "./data_types_requests";
import { GatewayEventList } from "./data_types";
import { GetGatewayEventListRequest } from "./data_types_requests";
import { SaveActionRequest } from "./data_types_requests";
import { AddActionRequest } from "./data_types_requests";
import { ActionEvent } from "./data_types";
import { DeleteActionEventRequest } from "./data_types_requests";
import { AddActionEventRequest } from "./data_types_requests";
import { ActionEventList } from "./data_types";
import { GetActionEventFilteredRequest } from "./data_types_requests";
import { DeleteActionRequest } from "./data_types_requests";
import { Action } from "./data_types";
import { GetActionByIdRequest } from "./data_types_requests";
import { SimpleActionList } from "./data_types";
import { GetActionFilteredRequest } from "./data_types_requests";
import { GatewayList } from "./data_types";
import { DeleteSeatingPlanRequest } from "./data_types_requests";
import { GetSeatingPlanFullData } from "./data_types";
import { SeatingPlan } from "./data_types";
import { GetSeatingPlanByIdRequest } from "./data_types_requests";
import { SimpleSeatingPlanList } from "./data_types";
import { GetSeatingPlanListRequest } from "./data_types_requests";
import { DeleteVenueRequest } from "./data_types_requests";
import { SaveVenueResponse } from "./data_types_requests";
import { SaveVenueRequest } from "./data_types_requests";
import { AddVenueResponse } from "./data_types_requests";
import { AddVenueRequest } from "./data_types_requests";
import { Venue } from "./data_types";
import { GetVenueByIdRequest } from "./data_types_requests";
import { GetVenueFilteredRequest } from "./data_types_requests";
import { SimpleVenueList } from "./data_types";
import { GetVenueByCityRequest } from "./data_types_requests";
import { DeleteCityRequest } from "./data_types_requests";
import { CityList } from "./data_types";
import { GetCityByCountryRequest } from "./data_types_requests";
import { City } from "./data_types";
import { DeleteCountryRequest } from "./data_types_requests";
import { Country } from "./data_types";
import { EOrganizerList } from "./data_types";
import { CurrencyList } from "./data_types";
import { ZoneIdList } from "./data_types";
import { GenreList } from "./data_types";
import { BookletTypeList } from "./data_types";
import { QuotaFormatList } from "./data_types";
import { BarcodeFormatList } from "./data_types";
import { VenueTypeList } from "./data_types";
import { KindList } from "./data_types";
import { SessionInfo } from "./auth_requests";
import { PrepareInitialDataResult } from "./auth_requests";
import { AuthCheckResult } from "./auth_requests";
import { AuthorizedRequest } from "./auth_requests";
import { AuthResult } from "./auth_requests";
import { AuthRequest } from "./auth_requests";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service auth.AuthGrpc
 */
export const AuthGrpc = new ServiceType("auth.AuthGrpc", [
    { name: "Auth", options: {}, I: AuthRequest, O: AuthResult },
    { name: "AuthCheck", options: {}, I: AuthorizedRequest, O: AuthCheckResult },
    { name: "PrepareInitialData", serverStreaming: true, options: {}, I: AuthorizedRequest, O: PrepareInitialDataResult },
    { name: "GetSessionInfo", options: {}, I: AuthorizedRequest, O: SessionInfo },
    { name: "GetInitialKindData", options: {}, I: AuthorizedRequest, O: KindList },
    { name: "GetInitialVenueTypeDataList", options: {}, I: AuthorizedRequest, O: VenueTypeList },
    { name: "GetInitialBarcodeFormatDataList", options: {}, I: AuthorizedRequest, O: BarcodeFormatList },
    { name: "GetInitialQuotaFormatDataList", options: {}, I: AuthorizedRequest, O: QuotaFormatList },
    { name: "GetInitialBookletTypeDataList", options: {}, I: AuthorizedRequest, O: BookletTypeList },
    { name: "GetInitialGenreDataList", options: {}, I: AuthorizedRequest, O: GenreList },
    { name: "GetZoneIdDataList", options: {}, I: AuthorizedRequest, O: ZoneIdList },
    { name: "GetInitialCurrencyDataList", options: {}, I: AuthorizedRequest, O: CurrencyList },
    { name: "GetInitialEOrganizerDataList", options: {}, I: AuthorizedRequest, O: EOrganizerList },
    { name: "GetInitialCountryData", serverStreaming: true, options: {}, I: AuthorizedRequest, O: Country },
    { name: "DeleteCountry", options: {}, I: DeleteCountryRequest, O: Country },
    { name: "GetInitialCityData", serverStreaming: true, options: {}, I: AuthorizedRequest, O: City },
    { name: "GetInitialCityByCountryData", serverStreaming: true, options: {}, I: GetCityByCountryRequest, O: City },
    { name: "GetInitialCityListByCountryData", options: {}, I: GetCityByCountryRequest, O: CityList },
    { name: "DeleteCity", options: {}, I: DeleteCityRequest, O: City },
    { name: "GetInitialVenueByCityData", options: {}, I: GetVenueByCityRequest, O: SimpleVenueList },
    { name: "GetInitialVenueDataFiltered", options: {}, I: GetVenueFilteredRequest, O: SimpleVenueList },
    { name: "GetInitialVenueByIdData", options: {}, I: GetVenueByIdRequest, O: Venue },
    { name: "AddVenue", options: {}, I: AddVenueRequest, O: AddVenueResponse },
    { name: "SaveVenue", options: {}, I: SaveVenueRequest, O: SaveVenueResponse },
    { name: "DeleteVenue", options: {}, I: DeleteVenueRequest, O: Venue },
    { name: "GetInitialSeatingPlanDataList", options: {}, I: GetSeatingPlanListRequest, O: SimpleSeatingPlanList },
    { name: "GetInitialSeatingPlanByIdData", options: {}, I: GetSeatingPlanByIdRequest, O: SeatingPlan },
    { name: "GetSeatingPlanByIdFullData", options: {}, I: GetSeatingPlanByIdRequest, O: GetSeatingPlanFullData },
    { name: "DeleteSeatingPlan", options: {}, I: DeleteSeatingPlanRequest, O: SeatingPlan },
    { name: "GetInitialSGatewayDataList", options: {}, I: AuthorizedRequest, O: GatewayList },
    { name: "GetInitialActionDataList", options: {}, I: GetActionFilteredRequest, O: SimpleActionList },
    { name: "GetInitialActionIdData", options: {}, I: GetActionByIdRequest, O: Action },
    { name: "DeleteAction", options: {}, I: DeleteActionRequest, O: Action },
    { name: "GetInitialActionEventDataList", options: {}, I: GetActionEventFilteredRequest, O: ActionEventList },
    { name: "AddActionEvent", options: {}, I: AddActionEventRequest, O: ActionEventList },
    { name: "deleteActionEvent", options: {}, I: DeleteActionEventRequest, O: ActionEvent },
    { name: "AddAction", options: {}, I: AddActionRequest, O: Action },
    { name: "SaveAction", options: {}, I: SaveActionRequest, O: Action },
    { name: "GetGatewayEventList", options: {}, I: GetGatewayEventListRequest, O: GatewayEventList },
    { name: "SaveActionEvent", options: {}, I: SaveActionEventRequest, O: ActionEvent },
    { name: "AddCountry", options: {}, I: AddCountryRequest, O: Country },
    { name: "SaveCountry", options: {}, I: SaveCountryRequest, O: Country },
    { name: "AddCity", options: {}, I: AddCityRequest, O: City },
    { name: "SaveCity", options: {}, I: SaveCityRequest, O: City },
    { name: "AddPlan1", options: {}, I: AddPlan1Request, O: SeatingPlan },
    { name: "CheckPlan", options: {}, I: CheckPlanRequest, O: CheckPlanResponse },
    { name: "AddPlan2", options: {}, I: AddPlan2Request, O: SeatingPlan },
    { name: "AddPlan3", options: {}, I: AddPlan3Request, O: SeatingPlan },
    { name: "SavePlan", options: {}, I: SavePlanRequest, O: SeatingPlan },
    { name: "SyncEts", options: {}, I: ActionEventSyncRequest, O: ActionEventSyncResponse },
    { name: "GetSyncReport", options: {}, I: GetSyncReportRequest, O: GetSyncReportResponse },
    { name: "GetGatewayEventInfo", options: {}, I: GetGatewayEventInfoRequest, O: GetGatewayEventInfoResponse },
    { name: "SetActionBooklet", options: {}, I: SetActionBookletRequest, O: SetActionBookletResponse }
]);
